# Generated by Django 5.2.3 on 2025-06-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='patients_photos/')),
                ('cas', models.CharField(max_length=50)),
            ],
        ),
    ]
