# Generated by Django 5.2.3 on 2025-06-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cas',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patients_images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='resultat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
